"""empty message

Revision ID: 67c6301f0121
Revises: 
Create Date: 2017-05-12 20:58:06.352204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c6301f0121'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('event_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('event_name')
    )
    op.create_table('event_player',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('is_playing', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('player_id', 'event_name')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player')
    op.drop_table('event_player')
    op.drop_table('event')
    # ### end Alembic commands ###
